/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorLoginRouteImport } from './routes/tutor.login'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ApiPublicHooksSyncTutorsRouteImport } from './routes/api/public/hooks/sync-tutors'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorLoginRoute = TutorLoginRouteImport.update({
  id: '/tutor/login',
  path: '/tutor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncTutorsRoute =
  ApiPublicHooksSyncTutorsRouteImport.update({
    id: '/api/public/hooks/sync-tutors',
    path: '/api/public/hooks/sync-tutors',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/c/$slug': typeof CSlugRoute
  '/r/$id': typeof RIdRoute
  '/tutor/login': typeof TutorLoginRoute
  '/api/public/hooks/sync-tutors': typeof ApiPublicHooksSyncTutorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/c/$slug': typeof CSlugRoute
  '/r/$id': typeof RIdRoute
  '/tutor/login': typeof TutorLoginRoute
  '/api/public/hooks/sync-tutors': typeof ApiPublicHooksSyncTutorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/c/$slug': typeof CSlugRoute
  '/r/$id': typeof RIdRoute
  '/tutor/login': typeof TutorLoginRoute
  '/api/public/hooks/sync-tutors': typeof ApiPublicHooksSyncTutorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/c/$slug'
    | '/r/$id'
    | '/tutor/login'
    | '/api/public/hooks/sync-tutors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/c/$slug'
    | '/r/$id'
    | '/tutor/login'
    | '/api/public/hooks/sync-tutors'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/c/$slug'
    | '/r/$id'
    | '/tutor/login'
    | '/api/public/hooks/sync-tutors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  CSlugRoute: typeof CSlugRoute
  RIdRoute: typeof RIdRoute
  TutorLoginRoute: typeof TutorLoginRoute
  ApiPublicHooksSyncTutorsRoute: typeof ApiPublicHooksSyncTutorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/login': {
      id: '/tutor/login'
      path: '/tutor/login'
      fullPath: '/tutor/login'
      preLoaderRoute: typeof TutorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-tutors': {
      id: '/api/public/hooks/sync-tutors'
      path: '/api/public/hooks/sync-tutors'
      fullPath: '/api/public/hooks/sync-tutors'
      preLoaderRoute: typeof ApiPublicHooksSyncTutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  CSlugRoute: CSlugRoute,
  RIdRoute: RIdRoute,
  TutorLoginRoute: TutorLoginRoute,
  ApiPublicHooksSyncTutorsRoute: ApiPublicHooksSyncTutorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
